# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX Sorry for small description. I'll make a better info soon. XXXXX#
name:         UkrMoney-API
version:      1.00
version_from: lib/UkrMoney/API.pm
installdirs:  site
requires:
    LWP::Simple:              0
    XML::Simple:       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
license: perl
